services:
    _defaults:
        public: false
        autowire: true

    harentius_blog.statistics_cache:
        class: Doctrine\Common\Cache\ApcuCache
        calls:
            - [ setNamespace, [ '%harentius_blog.cache.apc_global_prefix%_statistics' ] ]

    App\Statistics:
        arguments:
            $articleRepository: '@Harentius\BlogBundle\Entity\ArticleRepository'
            $cache: '@harentius_blog.statistics_cache'
            $cacheLifetime: '%statistics_cache_lifetime%'
