imports:
    - { resource: '@HarentiusBlogBundle/Resources/config/config.yml' }

services:
    App\Command\MarkdownExportCommand:
        public: true
        autowire: true
        tags:
            - { name: 'console.command' }
