doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your db driver and server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #driver: 'mysql'
        #server_version: '5.7'

        # Only needed for MySQL (ignored otherwise)
        charset: utf8mb4
        default_table_options:
            collate: utf8mb4_unicode_ci
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: 'doctrine.orm.naming_strategy.underscore'
        auto_mapping: true
        dql:
            datetime_functions:
                year: 'DoctrineExtensions\Query\Mysql\Year'
                month: 'DoctrineExtensions\Query\Mysql\Month'
        mappings:
            translatable:
                type: 'annotation'
                is_bundle: false
                prefix: 'Gedmo\Translatable\Entity'
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                alias: 'GedmoTranslatable'
