framework:
    secret: '%env(APP_SECRET)%'
    form:            false
    csrf_protection: ~
    validation:      { enable_attributes: true }
    default_locale:  '%locale%'
    session: ~
    fragments: ~
    http_method_override: true
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
