framework:
    secret: '%env(APP_SECRET)%'
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        form:
            resources:
                - 'SonataCoreBundle:Form:datepicker.html.twig'
        #assets_version: SomeVersionScheme
    default_locale:  '%locale%'
    session: ~
    fragments: ~
    http_method_override: true
    assets:
        json_manifest_path: '%kernel.project_dir%/public/build/manifest.json'
