harentius_blog:
    locales: ['en', 'uk', 'ru']
    primary_locale: 'ru'
    articles:
        image_previews_base_uri: '%image_previews_base_uri%'
    sidebar:
        # ~ - no cache, 0 - unlimited cache
        cache_lifetime: '%sidebar_cache_lifetime%'
        # Max tags number (ordered by max popularity)
        tags_limit: '%sidebar_tags_limit%'
        # Percent tags size, unlimited variants number (valid values: [50, 100], [25, 50, 75, 100], etc)
        tag_sizes: '%sidebar_tag_sizes%'
    homepage:
        # ~ - no page, feed only or page slug
        page_slug: '%homepage_page_slug%'
        # ~ - no feed
        feed:
            # ~ - all
            category: '%homepage_feed_category%'
            # Last articles number
            number: '%homepage_feed_number%'
    list:
        posts_per_page: '%list_posts_per_page%'
    # For avoiding internal apc cache conflicts if run multiple sites on one server.
    cache:
        apc_global_prefix: '%apc_global_prefix%'
