parameters:
    sharethis_product: 'inline-share-buttons'
    sharethis_property: '%env(SHARETHIS_PROPERTY)%'
    facebook_app_id: '%env(FACEBOOK_APP_ID)%'
    router.request_context.host: '%env(SITE_HOST)%'
    router.request_context.scheme: '%env(SITE_SCHEME)%'
