parameters:
    sidebar_cache_lifetime: null
    sidebar_tags_limit: 15
    sidebar_tag_sizes:
        - 65
        - 75
        - 83
        - 100
    homepage_page_slug: index
    homepage_feed_number: 7
    homepage_feed_category: null
    list_posts_per_page: 15
    statistics_cache_lifetime: 3600
    locale: ru
    generate_image_previews: true
    image_previews_base_uri: /assets/images/preview/
    apc_global_prefix: folkprog_net
    # Secret parameters
    secret: ThisTokenIsNotSoSecretChangeIt
    google_analytics.id: UA-40176382-1
    google_analytics.hostname: auto
    discuss_user_name: folkprog
    sharethis_property: 5a93088ce3b02a00133b311a
