version: '3.4'

services:
    blog_app:
        image: harentius/blog-bundle-base
        container_name: blogbundle_app
        volumes:
            - ./:/app
        links:
            - mysql

    mysql:
        image: mysql:5.7
        container_name: blogbundle_mysql
        environment:
            MYSQL_ROOT_PASSWORD: 1111
            MYSQL_PASSWORD: 1111
            MYSQL_DATABASE: blog
        command: mysqld --sql-mode=''

    selenium:
        image: selenium/standalone-chrome
        links:
            - blog_app
