pre_composer_script: |
    #!/bin/bash
    cp app/config/parameters.yml.dist app/config/parameters.yml

post_composer_script: |
    #!/bin/bash
    ./bin/console doctrine:database:create --no-interaction
    ./bin/console doctrine:schema:create --no-interaction
