language: php
php: '7.2'

cache:
  directories:
    - $HOME/.cache/composer

jobs:
  include:
    - stage: codestyle-check
      before_script:
        - composer global require friendsofphp/php-cs-fixer
      script:
        - $HOME/.composer/vendor/bin/php-cs-fixer --diff --dry-run --verbose fix ./src

    - stage: behavioral-tests
      sudo: required
      services:
        - docker
      before_script:
        - mkdir ./var/db-dumps
        - composer install --no-interaction
        - docker-compose -f support/ci/docker-compose.yml --project-directory=. up --build -d
        # Even after mysql fully started (it can be pinged by 'mysqladmin ping'),
        # there is still some time during which mysql for some reason is inaccessible by PDO.
        # Following workaround fixes that
        - |
          while ! docker exec -it folkprog_app php -r "new PDO('mysql:host=mysql', 'root', '1111');" ; do
            sleep 1;
          done
        - docker exec -it folkprog_app /app/bin/test-install
      script:
        - docker exec -it folkprog_app /app/vendor/bin/behat -c /app/behat.yml.dist

    - stage: deploy
      if: branch = master
      before_script:
        - composer install --no-interaction --no-dev
        - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
      script:
         - docker build "$IMAGE_NAME" support/prod/Dockerfile
         - docker push "${IMAGE_NAME}:latest"
