version: '3'
services:
    nginx:
        image: nginx:1.21
        ports:
            - "8080:80"
        volumes:
            - ./support/config/nginx/dev/folkprog.net:/etc/nginx/conf.d/default.conf
            - ./public:/app/public

    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./:/app
        environment:
            - COMPOSER_MEMORY_LIMIT=-1

    mysql:
        image: mariadb:10.6.4
        environment:
            MYSQL_ROOT_PASSWORD: '1111'
            MYSQL_USER: 'root'
            MYSQL_PASSWORD: '1111'
            MYSQL_DATABASE: 'folkprog'
        volumes:
            - mysqldata:/var/lib/mysql

volumes:
    mysqldata: {}
