services:
  nginx:
    image: nginx:1.27
    ports:
      - "8080:80"
    volumes:
      - ./support/dev/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./public:/app/public

  php:
    image: harentius/folkprog-php:latest
    volumes:
      - ./:/app
    environment:
      - COMPOSER_MEMORY_LIMIT=-1

  static:
    image: harentius/folkprog-static:latest

  mysql:
    image: mariadb:10.6.4
    environment:
      MARIADB_ROOT_PASSWORD: '1111'
      MARIADB_DATABASE: 'folkprog'
    volumes:
      - mysqldata:/var/lib/mysql
      #- "./var/folkprog.sql:/docker-entrypoint-initdb.d/1.sql"

  adminer:
    image: adminer
    ports:
      - 8090:8080
  # Can use something like this for editing frontend in the future (if needed)
  # node:
  #   image: node:14
  #   working_dir: /app/src/BlogBundle
  #   command: sh -c 'npm install && npm run watch'
  #   volumes:
  #     - ./:/app
  #   environment:
  #     OUTPUT_PATH: '../../public/bundles/harentiusblog/build'

volumes:
  mysqldata: {}
