services:
  nginx:
    image: nginx:1.27
    ports:
      - "8080:80"
    volumes:
      - ./support/dev/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./public:/app/public

  php:
    image: harentius/blog-php:latest
    volumes:
      - ./:/app
    environment:
      - APP_SECRET=dev_app
      - COMPOSER_MEMORY_LIMIT=-1
      - DATABASE_URL=mysql://root:1111@mysql:3306/blog
      - HISTFILE=/app/var/.bash_history-php
      - BLOG_TITLE=Web Developer Blog
      - THEME=dark
      - HIGHLIGHT_CODE=true

  static:
    image: harentius/blog-static:latest
    environment:
      - HISTFILE=/app/var/.bash_history-static

  mysql:
    image: mariadb:10.6.4
    environment:
      MARIADB_ROOT_PASSWORD: '1111'
      MARIADB_DATABASE: 'blog'
    volumes:
      - mysqldata:/var/lib/mysql
  # Uncomment it if you would like to load a backup
  #    - "./var/blog.sql:/docker-entrypoint-initdb.d/1.sql"

  # Uncomment it if you would like to see DB
  #adminer:
  #  image: adminer
  #  ports:
  #    - 8090:8080

volumes:
  mysqldata: {}
