# app/config/config.yml

sonata_block:
    default_contexts: [sonata_page_bundle]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

sonata_admin:
    templates:
        layout: HarentiusBlogBundle:Admin:standard_layout.html.twig
