blog_homepage:
    path:     /
    defaults: { _controller: HarentiusBlogBundle:Blog:index }

blog_archive:
    path:     /{year}/{month}
    defaults: { _controller: HarentiusBlogBundle:Blog:archive, month: null }
    requirements:
        year: \d+
        month: \d+

blog_list:
    path:     /{filtrationType}/{criteria}
    defaults: { _controller: HarentiusBlogBundle:Blog:list }
    requirements:
        filtrationType: category|tag

blog_show:
    path:     /{slug}
    defaults: { _controller: HarentiusBlogBundle:Blog:show }
