blog_index:
    path:     /
    defaults: { _controller: HarentiusBlogBundle:Blog:index }

blog_list:
    path:     /{filtrationType}/{criteria}
    defaults: { _controller: HarentiusBlogBundle:Blog:list }
    requirements:
        filtrationType: category|archive|tag
