login:
    path: login
    defaults: { _controller: HarentiusBlogBundle:Security:login }

login_check:
    path: login-check
    defaults: { _controller: HarentiusBlogBundle:Security:loginCheck }

sonata_admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'

_sonata_admin:
    resource: .
    type: sonata_admin
