services:
    harentius_blog.admin.article:
        class: Harentius\BlogBundle\Admin\ArticleAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Content, label: Articles, show_in_dashboard: true }
        arguments:
            - null
            - Harentius\BlogBundle\Entity\Article
            - HarentiusBlogBundle:CRUD
        calls:
            - [ setTranslationDomain, [HarentiusBlogBundle]]
            - [ setTemplate, [edit, HarentiusBlogBundle:Admin:edit.html.twig]]

    harentius_blog.admin.category:
        class: Harentius\BlogBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Content, label: Categories, show_in_dashboard: true }
        arguments:
            - null
            - Harentius\BlogBundle\Entity\Category
            - null
        calls:
            - [ setTranslationDomain, [HarentiusBlogBundle]]
