services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    harentius_blog.menu.menu_builder:
        class:  Harentius\BlogBundle\Menu\MenuBuilder
        arguments:
            - @knp_menu.factory
            - @doctrine.orm.entity_manager
            - %harentius_blog.homepage.page_slug%

    harentius_blog.menu.main:
        class: Knp\Menu\MenuItem
        factory_service: harentius_blog.menu.menu_builder
        factory_method: createMainMenu
        tags:
            - { name: knp_menu.menu, alias: main }

    harentius_blog.array_cache:
        class: Doctrine\Common\Cache\ArrayCache

    harentius_blog.sidebar.cache:
        class: Doctrine\Common\Cache\ApcCache
        calls:
            - [ setNamespace, [ harentius_blog_sidebar ] ]

    harentius_blog.twig.blog_extension:
        class: Harentius\BlogBundle\Twig\BlogExtension
        arguments:
            - @fragment.handler
            - ~
            - %sidebar_cache_filefime%
        tags:
            - { name: twig.extension }

    harentius_blog.sidebar.block:
        abstract: true
        calls:
            - [setEntityManager, [@doctrine.orm.entity_manager] ]

    harentius_blog.sidebar.categories:
        parent: harentius_blog.sidebar.block
        class: Harentius\BlogBundle\Sidebar\Categories

    harentius_blog.sidebar.tags:
        parent: harentius_blog.sidebar.block
        class: Harentius\BlogBundle\Sidebar\Tags
        arguments:
            - %harentius_blog.sidebar.tags_limit%
            - %harentius_blog.sidebar.tag_sizes%

    harentius_blog.sidebar.archive:
        parent: harentius_blog.sidebar.block
        class: Harentius\BlogBundle\Sidebar\Archive
