blog:
    resource: "@HarentiusBlogBundle/Resources/config/routing.yml"
    prefix:   /

app_page_about:
    path: /about
    defaults: { _controller: 'App\Controller\PageController' }

# Old site compatibility (slashes at the end)
harentius_blog_show_default:
    path: /{slug}/
    defaults: { _controller: 'Harentius\BlogBundle\Controller\ShowController' }

harentius_blog_show:
    path: /{_locale}/{slug}/
    defaults: { _controller: 'Harentius\BlogBundle\Controller\ShowController', _locale: '%kernel.default_locale%' }
    requirements:
        _locale: "%harentius_blog.locales_requirement%"
