harentius_blog_show_default:
    path:     /{slug}/
    defaults: { _controller: 'HarentiusBlogBundle:Blog:show', _locale: '%kernel.default_locale%' }

harentius_blog_show:
    path:     /{_locale}/{slug}/
    defaults: { _controller: 'HarentiusBlogBundle:Blog:show', _locale: '%kernel.default_locale%' }
# TODO
#    requirements:
#        _locale: "%harentius_blog.supported_locales_without_default%"
