imports:
    - { resource: '@HarentiusBlogBundle/Resources/config/packages/*' }

twig:
    globals:
        statistics: '@harentius_blog.statistics'

sonata_block:
    default_contexts: ['sonata_page_bundle']
    blocks: []
