imports:
    - { resource: '@HarentiusBlogBundle/Resources/config/packages/*' }

stof_doctrine_extensions:
    default_locale: '%locale%'
    orm:
        default:
            timestampable: true
            sluggable: true
            tree: true
            translatable: true
    translation_fallback: true

twig:
    globals:
        statistics: '@harentius_blog.statistics'

sonata_block:
    default_contexts: ['sonata_page_bundle']
    blocks: []

sonata_translation:
    locales: ['en', 'ru']
    default_locale: '%locale%'
    gedmo:
        enabled: true

liip_imagine:
    resolvers:
        default:
            web_path:
                cache_prefix: 'assets/images'
    filter_sets:
        preview:
            filters: []
