security:
    encoders:
        Harentius\BlogBundle\Entity\AdminUser: sha512

    providers:
        admin_users:
            entity:
                class: Harentius\BlogBundle\Entity\AdminUser
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        admin:
            pattern: ^/admin(.*)
            form_login:
                provider: admin_users
                login_path: login
                check_path: login_check
                default_target_path: sonata_admin_dashboard
            logout:
                path:   viosk_frontend_admin_logout
                invalidate_session: false
                target: homepage
            anonymous:    true
            remember_me:
                secret: '%secret%'
                lifetime: 31556926 # 1 year
                path:     /

    access_control:
         - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/admin(/|$), role: ROLE_ADMIN }
         - { role: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
