fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

PrestaSitemapBundle:
    resource: "@PrestaSitemapBundle/Resources/config/routing.yml"
    prefix:   /

admin:
    resource: "@HarentiusBlogBundle/Resources/config/routing-admin.yml"
    prefix:   /admin

blog:
    resource: "@HarentiusBlogBundle/Resources/config/routing.yml"
    prefix:   /

blog_override:
    resource: "@HarentiusFolkprogBundle/Resources/config/routing-override.yml"
    prefix:   /

widgets:
    resource: "@HarentiusWidgetsBundle/Resources/config/routing.yml"
