version: 2

jobs:
  lint:
    docker:
      - image: circleci/php:7.3-cli
    working_directory: ~/folkprog
    steps:
      - checkout
      - run: sudo composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "./vendor-bin/php-cs-fixer/composer.lock" }}
            - composer-v1-
          paths:
            - ./vendor-bin/php-cs-fixer/vendor
      - run: (cd ./vendor-bin/php-cs-fixer && composer install --no-interaction)
      - save_cache:
          key: composer-v1-{{ checksum "./vendor-bin/php-cs-fixer/composer.lock" }}
          paths:
            - ./vendor-bin/php-cs-fixer/vendor
      - run: composer cs-check

workflows:
  version: 2
  lint:
    jobs:
      - lint
