#!/usr/bin/env php
<?php

// if you don't want to setup permissions the proper way, just uncomment the following PHP line
// read http://symfony.com/doc/current/book/installation.html#configuration-and-setup for more information
//umask(0000);

set_time_limit(0);

require_once __DIR__.'/bootstrap.php.cache';
require_once __DIR__.'/AppKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Symfony\Component\Debug\Debug;

$input = new ArgvInput();
$readEnvFile = function () {
    $envFile = __DIR__.'/../.env';

    if (!is_file($envFile)) {
        return null;
    }

    $parts = explode(':', preg_replace('/\s+/', ' ', trim(file_get_contents($envFile))), 2);

    return array(
        isset($parts[0]) ? $parts[0] : null,
        isset($parts[1]) && $parts[1] === 'no-debug',
    );
};
list($envOverride, $noDebugOverride) = $readEnvFile();

$env = $input->getParameterOption(
    array('--env', '-e'),
    getenv('SYMFONY_ENV') ?: ($envOverride ?: 'dev')
);
$debug = getenv('SYMFONY_DEBUG') !== '0' && !$input->hasParameterOption(array('--no-debug', ''))
    && $env !== 'prod' && !$noDebugOverride
;
unset($readEnvFile, $envOverride, $noDebugOverride);

if ($debug) {
    Debug::enable();
}

$kernel = new AppKernel($env, $debug);
$application = new Application($kernel);
$application->run($input);
