version: '3.4'

volumes:
    blog_bundle_mysql_data: ~

services:
    blog_app:
        ports:
            - 8080:80

    mysql:
        volumes:
            - blog_bundle_mysql_data:/var/lib/mysql

    selenium:
        image: selenium/standalone-chrome-debug
        ports:
            - 5900:5900
