parameters:

services:
    _defaults:
        public: false
        autowire: true

    App\EventSubscriber\OverrideArticleRepositorySubscriber:
        tags:
            - { name: 'doctrine.event_subscriber' }

    App\Command\MarkdownExportCommand:
        tags:
            - { name: 'console.command' }
