imports:
    - { resource: 'services/*' }

parameters:

services:
    _defaults:
        public: false
        autowire: true

    App\EventSubscriber\OverrideArticleRepositorySubscriber:
        tags:
            - { name: 'doctrine.event_subscriber' }

    Harentius\BlogBundle\Menu\MenuBuilder:
        class: App\Menu\MenuBuilder
        arguments:
            $homepageSlug: '%harentius_blog.homepage.page_slug%'
