version: '3.4'

services:
    folkprog:
        image: harentius/blog-bundle-base
        container_name: folkprog_app
        links:
            - mysql
        volumes:
            - ./:/app
            - ./support/ci/nginx.vh.conf:/etc/nginx/conf.d/default.conf:ro
        links:
            - mysql
        environment:
            DATABASE_HOST: mysql
            DATABASE_PORT: 3306
            DATABASE_NAME: folkprog
            DATABASE_USER: root
            DATABASE_PASSWORD: 1111
    mysql:
        image: mysql:5.7
        container_name: folkprog_mysql
        environment:
            MYSQL_ROOT_PASSWORD: 1111
            MYSQL_PASSWORD: 1111
            MYSQL_DATABASE: folkprog
        command: mysqld --sql-mode=''

    selenium:
        image: selenium/standalone-chrome
        links:
            - folkprog
