version: '3.4'

services:
    folkprog:
        image: harentius/blog-bundle-base-php
        container_name: folkprog_app
        links:
            - mysql
        volumes:
            - ./:/app
            - ./support/ci/nginx.vh.conf:/etc/nginx/conf.d/default.conf:ro
        links:
            - mysql

    mysql:
        image: mysql
        container_name: folkprog_mysql
        environment:
            MYSQL_ROOT_PASSWORD: 1111
            MYSQL_PASSWORD: 1111
            MYSQL_DATABASE: folkprog
        command: mysqld --sql-mode=''

    selenium:
        image: selenium/standalone-chrome
        links:
            - folkprog
