stof_doctrine_extensions:
    default_locale: '%locale%'
    orm:
        default:
            timestampable: true
            sluggable: true
            tree: true
            translatable: true
    translation_fallback: true
