services:
    harentius_widgets.admin.widget:
        class: Harentius\WidgetsBundle\Admin\WidgetAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Content, label: Widgets, show_in_dashboard: true }
        arguments:
            - ~
            - Harentius\WidgetsBundle\Entity\Widget
            - ~
        calls:
            - [ setTranslationDomain, [HarentiusWidgetsBundle]]
            - [ setTemplate, [edit, HarentiusWidgetsBundle:Widget:edit.html.twig]]


    harentius_widgets.form.type.route:
        class: Harentius\WidgetsBundle\Form\Type\RouteType
        tags:
            - { name: form.type, alias: harentius_widget_route }

    harentius_widgets.form.type.route_fields:
        class: Harentius\WidgetsBundle\Form\Type\RouteFieldsType
        arguments:
            - @doctrine.orm.entity_manager
        tags:
            - { name: form.type, alias: harentius_widget_route_fields }

    harentius_widgets.form.type.position:
        class: Harentius\WidgetsBundle\Form\Type\PositionType
        tags:
            - { name: form.type, alias: harentius_widget_position }
