services:
    _defaults:
        public: true

    Harentius\BlogBundle\Admin\Controller\FileUploadController:
        arguments:
            - '@harentius_blog.assets.manager'

    Harentius\BlogBundle\Admin\Controller\SecurityController: ~
