version: 2

jobs:
  lint-php:
    docker:
      - image: circleci/php:7.3-cli
    steps:
      - checkout
      - run: sudo composer self-update
      - restore_cache:
          keys:
            - composer-bin-cs-fixer-v2-{{ checksum "vendor-bin/php-cs-fixer/composer.lock" }}
            - composer-bin-cs-fixer-v2-
      - run: (cd vendor-bin/php-cs-fixer && composer install --no-interaction)
      - save_cache:
          key: composer-bin-cs-fixer-v2-{{ checksum "vendor-bin/php-cs-fixer/composer.lock" }}
          paths:
            - vendor-bin/php-cs-fixer/vendor
      - run: composer cs-check

  lint-js:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: install-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: npm run lint

  phpstan:
    docker:
      -   image: circleci/php:7.3-cli
    steps:
      - checkout
      -   run: sudo composer self-update
      -   restore_cache:
            keys:
              - composer-v1-{{ checksum "composer.lock" }}
              - composer-v1-
      -   run: composer install --no-interaction --ignore-platform-reqs
      -   save_cache:
            key: composer-v1-{{ checksum "composer.lock" }}
            paths:
              - vendor
      -   run: composer phpstan

workflows:
  version: 2
  static:
    jobs:
      - lint-php
      - lint-js
      - phpstan
