framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    assets:
        packages:
            harentius_blog:
                json_manifest_path: '%kernel.project_dir%/public/bundles/harentiusblog/build/manifest.json'

stof_doctrine_extensions:
    default_locale: '%locale%'
    orm:
        default:
            timestampable: true
            sluggable: true
            tree: true
            translatable: true
    translation_fallback: true

twig:
    globals:
        statistics: '@harentius_blog.statistics'

cmf_routing:
    chain:
        routers_by_id:
            cmf_routing.dynamic_router: 200
            router.default:             100
    dynamic:
        enabled: true
        route_provider_service_id: 'harentius_blog.router.route_provider'

sonata_block:
    default_contexts: ['sonata_page_bundle']
    blocks: []

sonata_admin:
    templates:
        layout: 'HarentiusBlogBundle:Admin:layout.html.twig'
    dashboard:
        blocks: []

sonata_translation:
    locales: ['en', 'ru']
    default_locale: '%locale%'
    gedmo:
        enabled: true

knp_paginator:
    template:
        pagination: 'KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig'

white_october_breadcrumbs:
    separator: ~

liip_imagine:
    resolvers:
        default:
            web_path:
                cache_prefix: 'assets/images'
    filter_sets:
        preview:
            filters: []

doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your db driver and server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #driver: 'mysql'
        #server_version: '5.7'

        # Only needed for MySQL (ignored otherwise)
        charset: utf8mb4
        default_table_options:
            collate: utf8mb4_unicode_ci
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: 'doctrine.orm.naming_strategy.underscore'
        auto_mapping: true
        dql:
            datetime_functions:
                year: 'DoctrineExtensions\Query\Mysql\Year'
                month: 'DoctrineExtensions\Query\Mysql\Month'
        mappings:
            translatable:
                type: 'annotation'
                is_bundle: false
                prefix: 'Gedmo\Translatable\Entity'
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                alias: 'GedmoTranslatable'
