services:
    # default configuration for services in *this* file
    _defaults:
        public: false

    harentius_blog.sidebar.cache:
          class: Doctrine\Common\Cache\ApcuCache
          calls:
              - [ setNamespace, [ '%harentius_blog.cache.apc_global_prefix%_sidebar' ] ]

    harentius_blog.rating_cache:
        class: Doctrine\Common\Cache\ApcuCache
        calls:
            - [ setNamespace, [ '%harentius_blog.cache.apc_global_prefix%_rating' ] ]
