services:
    _defaults:
        public: true
        autowire: true

    Harentius\BlogBundle\Controller\FeedController: ~
    Harentius\BlogBundle\Controller\CategoryController: ~
    Harentius\BlogBundle\Controller\TagController: ~
    Harentius\BlogBundle\Controller\RateController: ~
    Harentius\BlogBundle\Controller\ImageOptimizationController: ~
