imports:
    - { resource: 'admin/*' }
    - { resource: 'controller.yaml' }

services:
    # default configuration for services in *this* file
    _defaults:
        public: false
        autowire: true

    Twig\Extensions\IntlExtension:
        tags:
            - { name: twig.extension }

    Harentius\BlogBundle\Menu\MenuBuilder:
        arguments:
            $homepageSlug: '%harentius_blog.homepage.page_slug%'

    Knp\Menu\MenuItem:
        factory: ['@Harentius\BlogBundle\Menu\MenuBuilder', 'createMainMenu']
        tags:
            - { name: knp_menu.menu, alias: main }

    harentius_blog.array_cache:
        class: Doctrine\Common\Cache\ArrayCache

    harentius_blog.twig.blog_extension:
        class: Harentius\BlogBundle\Twig\BlogExtension
        arguments:
            - '@twig.runtime.httpkernel'
            - ~
            - '@Harentius\BlogBundle\Rating'
            - '@harentius_blog.settings_provider'
            - '%harentius_blog.sidebar.cache_lifetime%'
            - '@harentius_blog.entity.translation'
            - '%harentius_blog.primary_locale%'
        tags:
            - { name: twig.extension }

    Harentius\BlogBundle\Twig\PublicationUrlGeneratorExtension:
        tags:
            - { name: twig.extension }

    harentius_blog.sidebar.tags:
        public: true
        class: Harentius\BlogBundle\Sidebar\Tags
        arguments:
            - '@harentius_blog.entity.tag_repository'
            - '%harentius_blog.sidebar.tags_limit%'
            - '%harentius_blog.sidebar.tag_sizes%'

    harentius_blog.sidebar.archive:
        class: Harentius\BlogBundle\Sidebar\Archive
        public: true
        arguments:
            - '@harentius_blog.entity.article_repository'

    harentius_blog.homepage:
        class: Harentius\BlogBundle\Homepage
        public: true
        arguments:
            - '@harentius_blog.entity.article_repository'
            - '@harentius_blog.entity.page_repository'
            - '%harentius_blog.homepage.feed.category%'
            - '%harentius_blog.homepage.page_slug%'

    Harentius\BlogBundle\Rating:
        arguments:
            $cache: '@harentius_blog.rating_cache'

    harentius_blog.views_counter:
        public: true
        class: Harentius\BlogBundle\ViewsCounter
        arguments:
            - '@session'
            - '@doctrine.orm.entity_manager'

    Harentius\BlogBundle\FileManagement\FilePathResolver:
        arguments:
            $webDir: '%kernel.project_dir%/public'

    Harentius\BlogBundle\FileManagement\FileManager: ~

    harentius_blog.settings_provider:
        class: Harentius\BlogBundle\SettingsProvider
        arguments:
             - '@harentius_blog.entity.setting_repository'
             - '@harentius_blog.settings.cache'

    harentius_blog.event_listener.sitemap_listener:
        class: Harentius\BlogBundle\Sitemap\SitemapSubscriber
        arguments:
            - '@router'
            - '@harentius_blog.homepage'
            - '@harentius_blog.entity.article_repository'
            - '@harentius_blog.entity.page_repository'
            - '@harentius_blog.entity.category_repository'
            - '%harentius_blog.homepage.page_slug%'
        tags:
            - { name: "kernel.event_subscriber", priority: 100 }

    harentius_blog.statistics:
        class: Harentius\BlogBundle\Statistics
        arguments:
            - '@harentius_blog.statistics_cache'
            - '%harentius_blog.cache.statistics_cache_lifetime%'
            - '@harentius_blog.entity.article_repository'

    Harentius\BlogBundle\FileManagement\Image\ImageOptimizer:
        arguments:
            - '@liip_imagine.cache.manager'
            - '@liip_imagine.filter.manager'
            - '@liip_imagine.data.manager'
            - '@Harentius\BlogBundle\FileManagement\FilePathResolver'
            - '%harentius_blog.articles.image_previews_base_uri%'

    Harentius\BlogBundle\EventListener\AdminUserListener:
        arguments:
            - '@security.password_encoder'
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }

    Harentius\BlogBundle\Router\PublicationUrlGenerator: ~

    Harentius\BlogBundle\BreadCrumbsManager: ~

    Harentius\BlogBundle\Paginator:
        arguments:
            $postsPerPage: '%harentius_blog.list.posts_per_page%'
