services:
    _defaults:
        public: false
        autowire: true
        tags:
            - { name: twig.extension }

    Twig\Extensions\IntlExtension: ~
    Harentius\BlogBundle\Twig\PublicationUrlGeneratorExtension: ~

    Harentius\BlogBundle\Twig\BlogExtension:
        arguments:
            - '@twig.runtime.httpkernel'
            - ~
            - '@Harentius\BlogBundle\Rating'
            - '@harentius_blog.settings_provider'
            - '%harentius_blog.sidebar.cache_lifetime%'
            - '@Harentius\BlogBundle\Entity\TranslationRepository'
            - '%harentius_blog.primary_locale%'
