harentius_blog_admin_home:
    path:     /admin
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: admin_harentius_blog_dashboard, permanent: true }

harentius_blog_admin_dashboard_redirect:
    path:     /dashboard
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: admin_harentius_blog_article_list, permanent: true }

harentius_blog_admin_file_upload:
    path: /file-upload
    defaults: { _controller: 'Harentius\BlogBundle\Admin\Controller\FileUploadController::upload' }
    options:
        expose: true

login:
    path: login
    defaults: { _controller: 'Harentius\BlogBundle\Admin\Controller\SecurityController::login' }

login_check:
    path: login-check
    defaults: { _controller: 'Harentius\BlogBundle\Admin\Controller\SecurityController::loginCheck' }

sonata_admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'

_sonata_admin:
    resource: .
    type: sonata_admin
